### DISCUSSION TITLE
Cocotb Kernel for Jupyter

### DISCUSSION THREAD

**Discussion by mmichilot** [cocotb/cocotb#3981] [Cocotb In The Wild]
I'm excited to finally release a Jupyter kernel that enables using cocotb within Jupyter notebooks! It's no longer an extension, but rather a simple Jupyter kernel that works for both JupyterLab and Jupyter Notebook Classic.

Here's a preview of it in action:
![DFlipFlopDemo](https://github.com/cocotb/cocotb/assets/22762462/ab1a101e-4af5-423d-8d92-9587d57cfb63)

Setting up the kernel for a project is simple by creating a `cocotb.toml` file within the project's root directory, similar to creating a  Makefile for cocotb.

Here's the TOML for the preview:
```toml
sim = "verilator"
hdl_toplevel = "dff"
hdl_toplevel_lang = "verilog"

[build]
verilog_sources = ["./dff.sv"]

[test]
waves = true

```

You can check it out at the [Github repo](https://github.com/mmichilot/cocotb_kernel) or check it out via binder:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/mmichilot/cocotb_kernel/HEAD?labpath=example%2FQuickstart+Guide.ipynb)

It's also available on PyPI: [cocotb_kernel](https://pypi.org/project/cocotb_kernel/)
To install it:
```bash
pip install cocotb_kernel
# Install the kernel to Jupyter's user directory
python -m cocotb_kernel.install --user 
```
